[2024-05-14T04:55:26.757+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T04:55:26.778+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_numbers_workflow.generate_random_numbers manual__2024-05-14T04:55:24.966135+00:00 [queued]>
[2024-05-14T04:55:26.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_numbers_workflow.generate_random_numbers manual__2024-05-14T04:55:24.966135+00:00 [queued]>
[2024-05-14T04:55:26.785+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-14T04:55:26.798+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_random_numbers> on 2024-05-14 04:55:24.966135+00:00
[2024-05-14T04:55:26.806+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=469) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T04:55:26.808+0000] {standard_task_runner.py:63} INFO - Started process 471 to run task
[2024-05-14T04:55:26.808+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_numbers_workflow', 'generate_random_numbers', 'manual__2024-05-14T04:55:24.966135+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/prioritas_2.py', '--cfg-path', '/tmp/tmp59i2wtdy']
[2024-05-14T04:55:26.811+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask generate_random_numbers
[2024-05-14T04:55:26.859+0000] {task_command.py:426} INFO - Running <TaskInstance: random_numbers_workflow.generate_random_numbers manual__2024-05-14T04:55:24.966135+00:00 [running]> on host 0391a550332e
[2024-05-14T04:55:26.943+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sinta' AIRFLOW_CTX_DAG_ID='random_numbers_workflow' AIRFLOW_CTX_TASK_ID='generate_random_numbers' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T04:55:24.966135+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T04:55:24.966135+00:00'
[2024-05-14T04:55:26.945+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T04:55:26.962+0000] {prioritas_2.py:20} INFO - Generated numbers: [17, 44, 3, 15, 47, 45, 36, 35, 43, 46, 14, 12, 44, 42, 44, 17, 42, 4, 29, 38, 10, 43, 41, 4, 1]
[2024-05-14T04:55:26.963+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T04:55:26.964+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T04:55:26.974+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_numbers_workflow, task_id=generate_random_numbers, run_id=manual__2024-05-14T04:55:24.966135+00:00, execution_date=20240514T045524, start_date=20240514T045526, end_date=20240514T045526
[2024-05-14T04:55:27.022+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T04:55:27.047+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-14T04:55:27.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
