[2024-05-20T08:36:50.715+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T08:36:50.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_api_data_and_write_to_files.done_message scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-20T08:36:50.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_api_data_and_write_to_files.done_message scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-20T08:36:50.775+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-20T08:36:50.804+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): done_message> on 2024-05-14 00:00:00+00:00
[2024-05-20T08:36:50.816+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=328) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T08:36:50.819+0000] {standard_task_runner.py:63} INFO - Started process 330 to run task
[2024-05-20T08:36:50.820+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_api_data_and_write_to_files', 'done_message', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '1630', '--raw', '--subdir', 'DAGS_FOLDER/prioritas_2.py', '--cfg-path', '/tmp/tmp0xb3faht']
[2024-05-20T08:36:50.824+0000] {standard_task_runner.py:91} INFO - Job 1630: Subtask done_message
[2024-05-20T08:36:50.972+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_api_data_and_write_to_files.done_message scheduled__2024-05-14T00:00:00+00:00 [running]> on host 0391a550332e
[2024-05-20T08:36:51.161+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sinta' AIRFLOW_CTX_DAG_ID='fetch_api_data_and_write_to_files' AIRFLOW_CTX_TASK_ID='done_message' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-05-20T08:36:51.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T08:36:51.166+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-20T08:36:51.168+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "done!"']
[2024-05-20T08:36:51.199+0000] {subprocess.py:86} INFO - Output:
[2024-05-20T08:36:51.201+0000] {subprocess.py:93} INFO - done!
[2024-05-20T08:36:51.203+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-20T08:36:51.205+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T08:36:51.247+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_api_data_and_write_to_files, task_id=done_message, run_id=scheduled__2024-05-14T00:00:00+00:00, execution_date=20240514T000000, start_date=20240520T083650, end_date=20240520T083651
[2024-05-20T08:36:51.316+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-20T08:36:51.345+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T08:36:51.348+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
